[package]
name = "exp_std"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
rand.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-test.workspace = true
chrono.workspace = true


[lints]
workspace = true
