words = [
    "aabbaa",
    "atoi",
    "bab",
    "babad",
    "bcb",
    "cbbd",
    "dcc",
    "eabcb",
    "fpalindrome",
    "iiiv",
    "kaabbaa",
    "lviii",
    "mcmxciv",
    "mmm",
    "mmmcmxcix",
    "mmmdccxlix",
    "nums",
    "pahnaplsiigyir",
    "paypalishiring",
    "pinalsigyahrpi",
    "МММ",
    "СМ",
]
