[package]
name = "rand_iterator"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
rand.workspace = true

[dev-dependencies]
criterion.workspace = true

[lints]
workspace = true


[[bench]]
name = "rand_iterator"
harness = false
